version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"

    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Asia/Jakarta"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "chore"
      include: "scope"

    pull-request-branch-name:
      separator: "-"

    labels:
      - "dependencies"
      - "dependabot"

    assignees:
      - "ahmadammarm"

    reviewers:
      - "ahmadammarm"

    versioning-strategy: auto
    rebase-strategy: auto

    groups:
      production-dependencies:
        dependency-type: "production"

      development-dependencies:
        dependency-type: "development"

      linting-tools:
        patterns:
          - "*eslint*"
          - "*prettier*"

    ignore:
      - dependency-name: "node"
        versions: ["<20"]

      - dependency-name: "@types/*"
        update-types:
          - "version-update:semver-patch"


  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"

    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Asia/Jakarta"

    open-pull-requests-limit: 3

    commit-message:
      prefix: "chore"
      include: "scope"

    pull-request-branch-name:
      separator: "-"

    labels:
      - "dependencies"
      - "github-actions"

    assignees:
      - "ahmadammarm"

    reviewers:
      - "ahmadammarm"
